-- MySQL Script generated by MySQL Workbench
-- 09/07/14 20:14:47
-- Model: New Model    Version: 1.0
--SET @@OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @O@LD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Votaai
-- -----------------------------------------------------
--CREATE SCHEMA [Votaai] DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
CREATE DATABASE [Votaai] ON  PRIMARY 
( NAME = N'Votaai', FILENAME = N'C:\Arquivos de Programas\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Votaai.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Votaai_1', FILENAME = N'C:\Arquivos de Programas\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Votaai_1.ldf' , SIZE = 25600KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

USE [Votaai]
go

--ALTER DATABASE [Votaai] SET COMPATIBILITY_LEVEL = 100
--GO

-- -----------------------------------------------------
-- Table Votaai.eleitor
-- -----------------------------------------------------
CREATE TABLE eleitor(
  eleitorid INT NOT NULL identity,
  nome VARCHAR(200) NOT NULL,
  tituloeleitor VARCHAR(15) NOT NULL,
  idade INT  NOT NULL,
  sexo CHAR NOT NULL,
  estado VARCHAR(60) NOT NULL,
  zonaeleitoral varchar(5) not null,
  secao varchar(6) not null,
  votou int NOT NULL,
  PRIMARY KEY (eleitorid))

-- -----------------------------------------------------
-- Table Votaai.partido
-- -----------------------------------------------------
CREATE TABLE partido (
  partidoid INT  NOT NULL identity,
  cnpj VARCHAR(15) NOT NULL,
  nome VARCHAR(300) NOT NULL,
  sigla VARCHAR(5) NOT NULL,
  prefixo VARCHAR(2) NOT NULL,
  PRIMARY KEY (partidoid))

-- -----------------------------------------------------
-- Table Votaai.candidato
-- -----------------------------------------------------
CREATE TABLE candidato (
  candidatoid INT  NOT NULL identity,
  nome VARCHAR(200) NOT NULL,
  numero VARCHAR(5) NOT NULL,
  cargo VARCHAR(100) NOT NULL,
  foto TEXT NOT NULL,
  partidoid INT  NOT NULL,
  PRIMARY KEY (candidatoid),
  --INDEX fk_candidato_partido_idx (partidoid ASC),
  CONSTRAINT fk_candidato_partido
    FOREIGN KEY (partidoid)
    REFERENCES partido (partidoid)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
-- -----------------------------------------------------
-- Table Votaai.voto
-- -----------------------------------------------------
CREATE TABLE voto (
  votoid INT  NOT NULL identity,
  estadoeleitor VARCHAR(2) NOT NULL,
  idadeeleitor INT NOT NULL,
  sexoeleitor CHAR NOT NULL,
  zonaeleitor varchar(5) not null,
  secaoeleitor varchar(6) not null,
  candidatoid INT  NOT NULL,
  PRIMARY KEY (votoid),
  --INDEX fk_voto_candidato1_idx (candidatoid ASC),
  CONSTRAINT fk_voto_candidato1
    FOREIGN KEY (candidatoid)
    REFERENCES candidato (candidatoid)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

-- -----------------------------------------------------
-- Table Votaai.usuario
-- -----------------------------------------------------
CREATE TABLE usuario (
  usuarioid INT NOT NULL identity,
  login VARCHAR(45) NOT NULL,
  senha VARCHAR(32) NOT NULL,
  PRIMARY KEY (usuarioid))

--SET SQL_MODE=@OLD_SQL_MODE;
--SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
--SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
